import "./globals.css";
import { Inter } from "next/font/google";
import LayoutProvider from "@/components/layout-provider/layout-provider";
import Toast from "@/utils/toast";
import Provider from "@/utils/session-provider";
import "react-loading-skeleton/dist/skeleton.css";
import 'react-confirm-alert/src/react-confirm-alert.css'; 
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `} >
        <Provider>
          <Toast />
          <LayoutProvider>{children}</LayoutProvider>
        </Provider>
      </body>
    </html>
  );
}
